In [ ]:
import pandas as pd # khai báo thư viện pandas và khai báo nó là pb
import numpy as np # khai báo thư viện numpy và khai báo nó là np
# khai báo biến để đọc dữ liệu từ file heart.csv
dataR = pd.read_csv("heart.csv"); 
data = dataR

In [ ]:
# dùng hàm unique() lọc giá trị duy nhất trong cột HeartDisease
data["HeartDisease"].unique() 

array([0, 1])

In [ ]:
# lọc các cột là số trên data
duLieuSo = [a for a in data.columns if data[a].dtypes != 'O']
# hiển thị độ dài cho duLieuSo
print("So cot du lieu so :",len(duLieuSo))
# in ra duLieuSo
data[duLieuSo]

So cot du lieu so : 7


Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
0     40        140          289          0    172      0.0             0
1     49        160          180          0    156      1.0             1
2     37        130          283          0     98      0.0             0
3     48        138          214          0    108      1.5             1
4     54        150          195          0    122      0.0             0
..   ...        ...          ...        ...    ...      ...           ...
913   45        110          264          0    132      1.2             1
914   68        144          193          1    141      3.4             1
915   57        130          131          0    115      1.2             1
916   57        130          236          0    174      0.0             1
917   38        138          175          0    173      0.0             0

[918 rows x 7 columns]

In [ ]:
# lọc các cột là chữ trên data
duLieuChu = [a for a in data.columns if data[a].dtypes == 'O']
# hiển thị độ dài cho duLieuChu
print("So cot du lieu chu :",len(duLieuChu))
# in ra duLieuChu
data[duLieuChu]

So cot du lieu chu : 5


Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0     M           ATA     Normal              N       Up
1     F           NAP     Normal              N     Flat
2     M           ATA         ST              N       Up
3     F           ASY     Normal              Y     Flat
4     M           NAP     Normal              N       Up
..   ..           ...        ...            ...      ...
913   M            TA     Normal              N     Flat
914   M           ASY     Normal              N     Flat
915   M           ASY     Normal              Y     Flat
916   F           ATA        LVH              N     Flat
917   M           NAP     Normal              N       Up

[918 rows x 5 columns]

In [ ]:
data.isnull().sum() #Kiểm tra các cột có dữ liệu null không

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
# chuẩn hóa dữ liệu từ chữ sang số
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for a in duLieuChu:
    print(data[a].unique())
    data[a]=label_encoder.fit_transform(data[a]) 
    print(data[a].unique())
data

[1 0]
[1 0]
[1 2 0 3]
[1 2 0 3]
[1 2 0]
[1 2 0]
[0 1]
[0 1]
[2 1 0]
[2 1 0]


Age  Sex  ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0     40    1              1  ...      0.0         2             0
1     49    0              2  ...      1.0         1             1
2     37    1              1  ...      0.0         2             0
3     48    0              0  ...      1.5         1             1
4     54    1              2  ...      0.0         2             0
..   ...  ...            ...  ...      ...       ...           ...
913   45    1              3  ...      1.2         1             1
914   68    1              0  ...      3.4         1             1
915   57    1              0  ...      1.2         1             1
916   57    0              1  ...      0.0         1             1
917   38    1              2  ...      0.0         2             0

[918 rows x 12 columns]

In [ ]:
# Chia data thành 2 phần test và train
from sklearn.model_selection import train_test_split
y = data["HeartDisease"]
X = data.drop("HeartDisease", axis=1)
# chia X(y) thành x(y)_train, x(y)_test bằng hàm train_test_split với 10% dữ liệu để test và 90% để train
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.1, random_state = 0) 
# in ra độ dài 4 thành phần trên
len(X_train), len(X_test), len(y_train), len(y_test)

(826, 92, 826, 92)

In [ ]:
# tạo cây quyết định
from sklearn.tree import DecisionTreeClassifier
#Tạo cây quyết định với độ sâu 4
treeD = DecisionTreeClassifier(criterion = "entropy", max_depth = 4, min_samples_leaf = 10) 
treeD.fit(X_train, y_train) #Khởi tạo cây quyết định từ tập dữ liệu train

DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=10)

In [ ]:
#Dự đoán kết quả test trả về khi đưa tập test vào
y_predict = treeD.predict(X_test) 
print("Tập dữ liệu dự đoán: ", y_predict)
print("Tập dữ liệu có test: ", np.array(y_test))

Tập dữ liệu dự đoán:  [1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1
 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 1
 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 0 0 1]
Tập dữ liệu có test:  [1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1
 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1
 1 1 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1]


In [ ]:
# in ra độ chính xác model
from sklearn.metrics import accuracy_score
print('Độ chính xác của model: {0:0.4f}'. format(accuracy_score(y_test, y_predict)))

Độ chính xác của model: 0.8804


In [ ]:
# ????
print('Điểm train: {:.4f}'.format(treeD.score(X_train, y_train)))
print('Điểm test: {:.4f}'.format(treeD.score(X_test, y_test)))

Điểm train: 0.8584
Điểm test: 0.8804


In [ ]:
# Vẽ mô hình cây quyết định với các thuộc tính là các cột còn lại trong bảng dữ liệu trừ cột đự đoán
from sklearn.tree import export_graphviz
features = ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope']
export_graphviz( treeD,
        out_file=r"/tree.dot",
        feature_names=features,
        class_names=['0', '1'],
        rounded=True, filled=True, leaves_parallel=True, 
        node_ids=True, proportion=False, precision=2 )

In [ ]:
# lưu cây đã tạo vào file pdf
from graphviz import Source
Source.from_file(r"/tree.dot").render(r"/tree", format='pdf', view=True, cleanup=True)

'/tree.pdf'